name: Git linter

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint Commit Messages

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Fetch and checkout
        run: git fetch origin && git checkout ${{ github.head_ref }}
      - name: Event Sender
        run: echo ${{ github.event.sender.login }}
        